let arrLang = {
    'ru':{
        'btn-1' : 'Заказать',
        'btn-2' : 'Скидки',
        'btn-3' : 'Доставка бесплатно',
        'kateg' : 'наши товары',
        'reviews' : 'отзывы',
        'contact' : 'свяжитесь с нами',
        'new' : 'Новая коллекция',
        'korrektor-intro' : 'Корректор для',
        'intro-pillow' : 'Ортопедическая',
        'intro-pillow2' : 'Ортопедический',
        'intro-vorotnik': 'Ортопедический',
        'intro-span1' : 'осанки',
        'intro-span2' : 'подушка',
        'intro-span3' : 'воротник',
        'intro-span4' : 'бандаж',
        'intro-bandaj' : 'Колленый',
        'intro-vorotnik' : 'Ортопедический',
        
        'intro-p' : 'Купите наш качественный ортопедический корректор для вашего здоровья',
        'intro-p2': 'Купите качественный ортопедический воротник для вашего здоровья',
        'intro-p3': 'Купите нашу качественную ортопедическую подушку для вашего здоровья',
        'intro-p4': 'Купите нашу качественную повязку на колено для вашего здоровья',
        'intro-btn': 'купить сейчас',
        'korset' : 'Ортопедический корсет',
        'vorotnik' : 'Ортопедичекий воротник',
        'yostig' : 'Ортопедическая подушка',
        'bandaj' : 'Коленный бандаж',
        'sum1' : '240 000 сум',
        'sum2' : '150 000 сум',
        'sum3' : '420 000 сум',
        'sum4' : '320 000 сум',
        'varienty' : 'гарантия',
        'delivery' : 'доставка',
        'pay' : 'оплата',
        'varienty-p' : 'Гарантия на изделие действует только при соблюдении вышеперечисленных правил при использовании ортопедических изделий. для его эксплуатации и обслуживания.',
        'delivery-p' : 'Высокая безопасность и конфиденциальность службы доставки, гибкость, лояльность клиентов и доступные цены — наши главные приоритеты.',
        'pay-p': 'Не бойтесь, что я оплачу сразу, когда будет оплата? Вы можете оплатить после получения нашей продукции, и наша продукция будет доставлена ​​к вам домой бесплатно',
        'btn-product' : "подробнее",
        'pillow-p': 'Ортопедическая подушка – специально разработанное средство для комфортного сна. Гарантирует естественное положение позвоночника, шейный и грудной отделы вычерчивают прямую линию, нет перегрузки на межпозвонковые диски.',
        'korset-p' : 'Ортопедический корсет представляет собой медицинский ортопедический пояс из дышащей, эластичной ткани со специальными ремнями жесткости и натяжения, применяемый при заболеваниях, искривлениях и травмах позвоночника.',
        'product-korset' : 'Фиксирующий корсет',
        'korset-span' : 'для спины',
        'product-vorotnik' : "Массажный воротник",
        'vorotnik-span' : 'для шеи',
        'vorotnik-p' : 'Массажный шейный воротник — это мягкий шейный бандаж, который ограничивает движения шеи. Изготовлен из мягкого пеноматериала, оборачивается вокруг шеи и застегивается сзади. Фиксация шейным воротником применяется для лечения мышечных спазмов, стабилизации и ограничения движений в шейном отделе.',
        'product-bandaj' : 'Разъемная конструкция',
        'bandaj-span' : 'коленного бандажа',
        'bandaj-p' : 'Коленный бандаж — это ортопедический бандаж для ног, который надевается на коленный сустав и используется для его стабилизации и стабилизации надколенника, мениска и связок.',
        'comment' : 'Комментарии',
        'comments' : 'ЧТО ГОВОРЯТ ',
        'comments-span' : ' НАШИ КЛИЕНТЫ',
        'com-1' : 'Подушка, конечно, не из дешевых, но решил такую жене на день рождения. Подушка обладает эффектом памяти и принимает форму тела, очень приятный чехол, забрал сразу из магазина. Качество продукции хорошее, как и сервис и обслуживание. Жена спит на ней почти год и за это время подушка не потеряла форму и не скаталась.',
        'com-2' : 'Здравствуйте! Я купила такую подушку своей дочке! мягкая, удобная, приятная... нам посоветовал аллерголог сменить перо-пуховую подушку, мы решили отдать предпочтение именно этой подушке и очень довольны! Жесткость - сорок. само то... упакована в тубус. Чехол съемный легко ухаживать, розовый- что очень мило для девочек.',
        'com-3' : "Время от времени я борюсь с шейным остеохондрозом.В очередной раз, когда я пошла в ортопедический магазин за подушкой для спины, я обнаружила интересное приспособление, вернее это считается подушкой, и пошла изучать информацию о ней.  И спустя небольшой промежуток времени, заветная коробочка была у меня в руах!",
        'com-4' : 'Действильно помогает спине, очень хорошо и аккуратно все сшито, черный!!никогда бы не подумал,что вещь из онлайн магазина может быть такой качественной и надежной в использовании. здесь залепил, там натянул и все держится, никто даже ее помогает одевать. внутри какие-то еще костяшки для жесткости.рекомендую!',
        'com-5' : 'Классный корсет для поясницы. Как-то у меня прихватило спину и подруга пришла меня спасать, принесла всякие разные мази и этот корсет. Я встала на ноги практически на следующий день. После этого случая решила заказать себе такой корсет, чтоб экстренно всегда меня спасал. Удивила цена, сейчас по такой стоимости практически ничего толкового найти невозможно.',
        'com-6' : 'Взял для вытягивания шеи. - Выключение болевого синдрома от шейных небольших грыж. Хочется оказаться в числе тех, кто эти грыжи уменьшил. И дальше занимается любимыми делами без ограничений.',
        'com-7' : 'Хорошая идея, действительно вытягивает шейные позвонки. Были сильные боли в обеих руках,у меня шейная грыжа,одела воротник и боль практически прошла. Кто знаком с этой болью,тот знает,что такое хотя бы пятиминутный перерыв! После сеанса боль конечно вернулась,но не такая сильная. Буду увеличивать время сеансов. ',
        'contact-p': "Свяжитесь с нами",
        'contact-h2' : "ЗАПОЛНИТЕ",
        'contact-span' : "ФОРМУ",
        'inp-1' : "ваше имя*",
        'send' : 'ОТПРАВИТЬ',
        'info' : 'Инфо',
        'menu' : 'Меню',
        'all': 'Все продукты',
        'reviews': 'отзывы',
        'contact': "свяжитесь с нами",
        'network' : 'Наши соц.сети',
        'rights' : 'Все права защищены © 2022',
        'home' : 'главная',
        'interesting' : 'Исследуйте удивительные',
        'about' : 'ПРОДУКТЕ',
        'pillow-sp' : '- это специально разработанное средство для комфортного сна. Она гарантирует позвоночнику естественное положение, шейный и грудной отделы вычерчивают прямую линию, нет излишней нагрузки на межпозвонковые диски.Волнообразная форма создает необходимую поддержку шеи в положении на спине. Ортопедические свойства подушки обеспечивают крепкий сон, полное расслабление, восстановление за ночь и бодрость по утрам. Кроме того, он обладает высокой пластичностью и равномерно распределяет нагрузку по всей поверхности подушки.',
        'main1': 'ОСНОВНЫЕ',
        'main2': 'ОСОБЕННОСТИ',
        'main-p' : 'Покупайте нашу высококачественную корректор для твое здоровье',
        'material' : 'Материал',
        'repeir' : 'Лечение и профилактика',
        'ekologiya' : "Экология и эргономика",
        'use' : 'ПОКАЗАНИЯ К',
        'show' : 'ПРИМЕНЕНИЮ',
        'contact-title' : 'Хотите',
        'contact-text' : 'Заказать?',
        'buy' : 'купить',
        'sum5' : '450 000 сум',
        'vorotnik2' : 'Массажный воротник для шеи',
        'korset2' : 'Фиксирующий корсет для спины',
        'bandaj2' : 'Разъемная конструкция коленного бандажа',
        'sum6' : '260 000 сум',
        'intro-korset' : 'корсет',
        'product' : 'О',
        'about-korset' : '- медицинский ортопедический пояс из воздухопроницаемой, эластичной ткани со специальными ребрами жесткости и стягивающими ремнями, применяемый при заболеваниях, искривлениях и травмах позвоночника. Миллионы людей страдают от той или иной формы болей в спине. Большинство болевых синдромов вызвано периодическим неправильным переносом веса на нижнюю часть спины. Таким образом, корсет для спины помогает снять эту нагрузку, тем самым уменьшая давление, оказываемое на суставы позвоночника, межпозвоночные диски и мышцы нижней части спины. Разгрузка устраняет болезненное напряжение мышц, тем самым обеспечивая здоровое положение позвоночника. Корсеты для спины обеспечивают дополнительную стабильность позвоночника, компенсируя боль и дискомфорт при любой деятельности, а также помогая в лечении и восстановлении после самых разных травм и состояний.',
        'about-vorotnik':' - это мягкий шейный воротник, который ограничивает движения шеи. Изготовлен из мягкого пеноматериала, оборачивает шею и застегивается сзади. Фиксацию шейным воротником используют для лечения мышечных спазмов, стабилизации и ограничения движений в шейном отделе.',
        'about-bandaj' : '– это ортопедический бандаж для ног, который надевается в области коленного сустава и используется для его стабилизации и стабилизации надколенника, поддержки мениска и связок. На рынке представлено несколько типов изделий, которые носят общее название “наколенник”, но выполняют разные функции и назначаются при разных медицинских показаниях. Некоторые типы наколенников можно купить самостоятельно, другие выбираются только по рекомендации врача, тренера или физиотерапевта. В любом случае, достаточно часто неопытный потребитель не до конца понимает что это такое – наколенники, и какой именно тип изделия подходит именно ему. Специально для таких случаев мы подготовили развернутую статью, в которой рассмотрим основные типы ортопедических наколенников, их функцию и особенности применения.',
        'podushka-p1' : 'Остеохондроз, вызванный дистрофией межпозвоночных дисков.',
        'podushka-p2' : 'Головные боли и вертебробазилярная недостаточность, связанные с нарушением кровообращения мозга.',
        'podushka-p3' : 'Болевые ощущения в мышцах шеи и их воспаление, провоцируемые повышенной нагрузкой во время сна.',
        'podushka-p4' : 'Нарушение работы вестибулярного аппарата.',
        'podushka-p5' : 'Мышечный дисбаланс, вызываемый продолжительным статичным положением тела или стереотипно-повторяющимися действиями.',
        'karset-p1' : "Cильная сутулость, ослабленные спинные мышцы.",
        'karset-p2' : "Острые или хронические заболевания спинного отдела.",
        'karset-p3' : "Врожденные или хронические нарушения позвоночника.",
        'karset-p4' : "Профилактика поражений опорно-двигательной системы.",
        'karset-p5' : "Сохранение нормальной осанки при различных заболеваниях позвоночника.",
        'bandaj-p1': 'Ушибы в области коленного сустава.',
        'bandaj-p2' : 'Боли в коленном суставе при движении и в покое.',
        'bandaj-p3' : 'Лёгкая нестабильность коленного сустава.',
        'bandaj-p4' : 'Отёки в области колена при артрозах, артритах, синовитах, бурситах.',
        'bandaj-p5' : 'Профилактика обострений хронических воспалительных заболеваний в области коленного сустава (артриты, бурситы, синовиты, артрозы).',
        'vorotnik-p1' : 'Боли в шейном отделе и спине разного характера.',
        'vorotnik-p2' : 'Дегенеративно-дистрофические заболевания позвоночника.',
        'vorotnik-p3' : 'Избыточное отложение жира в подбородочной области.',
        'vorotnik-p4' : 'Шейный спондилез, шейный радикулитный синдром.',
         'vorotnik-p5' : 'Реабилитация после травм, послеоперационные состояния на шейном отделе позвоночника, реабилитация после оперативного лечения грыж межпозвонковых дисков.',
         'privacy-h3': "Поддержка",
        'privacy-p1': 'Правовая политика',
        'privacy-p2': 'Политика конфиденциальности',
        'privacy-p3': 'Условия обслуживания',
    },
    'uz':{
        'btn-1' : 'Buyurtma berish',
        'btn-2' : 'Chegirma',
        'btn-3' : 'Yetkazib berish bepul',
        'kateg' : 'bizni mahsulotlar',
        'home' : 'bosh sahifa',
        'reviews' : 'sharhlar',
        'contact' : "biz bilan bog'laning",
        'new' : "Yangi to'plam",
        'korrektor-intro' : 'Belingiz uchun',
        'intro-pillow' : 'Ortopedik',
        'intro-pillow2' : 'Ortopedik',
        'intro-bandaj' : 'Tizza uchun',
        'intro-vorotnik' : 'Ortopedik',
        
        'intro-span1' : 'korrektor',
        'intro-span2' : 'yostig',
        'intro-span3' : 'vorotnik',
        'intro-span4' : 'bandaj',
        'intro-p' : "Sog'ligingiz uchun sifatli ortopedik korrektorimizni sotib oling",
        'intro-p2': "Sog'ligingiz uchun sifatli ortopedik yoqasini sotib oling",
        'intro-p3': "Sog'ligingiz uchun bizning sifatli ortopedik yostiqimizni sotib oling",
        'intro-p4': "Sog'ligingiz uchun bizning sifatli tizza uchun bandajimizni sotib oling",
        'intro-btn': 'hozir sotib olish',
        'buy' : 'sotib olish',
        'korset' : 'Ortopedik korset',
        'korset2' :"Belingiz uchun korset ",
        'vorotnik' : 'Ortopedik vorotnik',
        'vorotnik2' : "Bo'yin uchun massajli vorotnik",
        'yostig' : 'Ortopedik yostig',
        'bandaj' : 'Tizza uchun bandaj',
        'sum1' : '240 000 sum',
        'sum2' : '150 000 sum',
        'sum3' : '420 000 sum',
        'sum4' : '320 000 sum',
        'sum5' : '450 000 sum',
        'sum6' : '260 000 sum',
        'intro-korset' : 'korset',
        'badaj2' : 'Echib olinadigan tizza bandaji',
        'menu' : 'Menu',
        'varienty' : 'kafolat',
        'delivery' : 'yetkazib berish',
        'pay' : "to'lov",
        'varienty-p' : "Mahsulot kafolati faqat ortopedik mahsulotlardan foydalanishda yuqoridagi qoidalarga rioya qilingan taqdirdagina amal qiladi uni ishlatish va texnik xizmat ko'rsatish uchun.",
        'delivery-p' : "Yetkazib berish xizmatida yuqori darajadagi xavfsizlik va maxfiylik, moslashuvchanlik, mijozlarga sadoqat va hamyonbop narxlar – bizning ishdagi ustuvorligimizdir.Mahsulotlar o'z vaqtida yetib boradi.",
        'pay-p' : "To'lovni birdan qilaman deb qo'rqmang to'lov qachon qilinadi? To'lovni siz mahsulotimizni qo'lizga olgandan keyin qila olasiz va bizni mahsulotlarimiz sizni uyizgacha bepul yetkazib beriladi",
        'btn-product': "KO'PROQ MA'LUMOT OLISH",
        'pillow-p': "Ortopedik yostiq qulay uyqu uchun maxsus mo'ljallangan vositadir. U umurtqa pog'onasining tabiiy holatini kafolatlaydi, servikal va torakal bo'limlar to'g'ri chiziq chizadi, intervertebral disklarda ortiqcha yuk yo'q.",
        'korset-p' : "Ortopedik korset - umurtqa pog'onasi kasalliklari, egriligi va shikastlanishlarida qo'llaniladigan maxsus qattiqlashtiruvchi va tortuvchi tasmalar bilan nafas oladigan, elastik matodan tayyorlangan tibbiy ortopedik kamar.",
        'product-korset' : 'Belni tuzatish uchun',
        'korset-span' : 'korset',
        'product-vorotnik' : "Bo'yin uchun  massajli",
        'vorotnik-span' : 'vorotnik',
        'vorotnik-p' : "Massajli vorotnik yumshoq bo'yinbog' bo'lib, bo'yin harakatlarini cheklaydi. Yumshoq ko'pikdan yasalgan bo'lib, bo'yniga o'raladi va orqa tomondan mahkamlanadi. Servikal bo'yinbog' bilan fiksatsiya mushaklarning spazmlarini davolash, servikal mintaqadagi harakatlarni barqarorlashtirish va cheklash uchun ishlatiladi.",
        'product-bandaj' : 'Tizza uchun',
        'bandaj-span' : 'bandaj',
        'bandaj-p' : "Echib olinadigan tizza belbog'i - bu tizza bo'g'imi hududida kiyiladigan va uni barqarorlashtirish va patellani barqarorlashtirish, meniskus va ligamentlarni qo'llab-quvvatlash uchun ishlatiladigan ortopedik oyoq qavs.",
        'comment' : 'Izohlar',
        'comments' : 'MIJOZLARNING',
        'comments-span' : 'FIKRI',
        'com-1' : "Yostiq, albatta, arzon emas, lekin men uning tug'ilgan kuni uchun bunday xotinga qaror qildim. Yostiq xotira effektiga ega va tananing shaklini oladi, juda chiroyli qopqoq, men uni darhol do'kondan oldim. Mahsulot sifati, xizmat ko'rsatish va texnik xizmat ko'rsatish kabi yaxshi. Xotinim deyarli bir yil davomida uxlab yotgan va bu vaqt ichida yostiq o'z shaklini yo'qotmagan va o'ralgan emas.",
        'com-2' : "Salom! Men bu yostiqni qizim uchun sotib oldim! yumshoq, qulay, yoqimli ... bizga allergist tukli yostiqni almashtirishni maslahat berdi, biz ushbu maxsus yostiqqa ustunlik berishga qaror qildik va juda mamnunmiz! Qattiqlik - qirq. Aynan narsa ... naychaga o'ralgan. Qopqoq olinadigan va parvarish qilish oson, pushti qizlar uchun juda yoqimli.",
        'com-3' : "Vaqti-vaqti bilan men servikal osteoxondroz bilan kurashaman.Yana bir bor orqa yostiq uchun ortopediya do'koniga borganimda, men qiziqarli moslamani topdim, to'g'rirog'i, u yostiq hisoblanadi va u haqida ma'lumot o'rganish uchun bordim. Va qisqa vaqt o'tgach, qimmatbaho quti mening ruachimda edi!",
        'com-4' : "Bu, albatta, orqaga yordam beradi, hamma narsa juda yaxshi va ozoda tikilgan, qora!!Men hech qachon onlayn do'kondagi narsa bunchalik sifatli va foydalanishda ishonchli bo'lishi mumkin deb o'ylamagan edim. Men uni shu yerda yamab qo'ydim, tortdim va hamma narsa ushlab turdi, hech kim uni kiyintirishga yordam bermaydi. Qattiqlik uchun yana bir nechta bo'g'imlar ichida. Tavsiya qilaman!",
        'com-5' : "Zo'r korset bel uchun. Negadir belim ushlandi va bir do'stim meni qutqargani keldi, har xil moylar va bu korsetni olib keldi. Men deyarli ertasi kuni ishga tushdim. Ushbu voqeadan keyin men o'zim uchun bunday korsetni buyurtma qilishga qaror qildim, shunda u meni doimo zudlik bilan qutqaradi. Men narxdan hayratda qoldim, endi bunday narxda oqilona narsani topish deyarli mumkin emas.",
        'com-6' : "Bo'yinni cho'zish uchun oldi. - bachadon bo'yni kichik churralaridan og'riq sindromini to'xtatish. Men bu churralarni kamaytirganlar qatorida bo'lishni istardim. Keyin esa cheklovsiz sevgan ishini qiladi.",
        'com-7' : "Yaxshi fikr, albatta, bachadon bo'yni umurtqalarini cho'zadi. Ikkala qo'limda qattiq og'riqlar bor edi, menda bo'yin churrasi bor, men yoqani qo'ydim va og'riq deyarli yo'qoldi. Bu og'riq bilan tanish bo'lganlar kamida besh daqiqalik tanaffus nima ekanligini bilishadi! Seansdan keyin og'riq, albatta, qaytdi, lekin unchalik kuchli emas. Men sessiya vaqtini oshiraman.",
        'contact-p': "Biz bilan bog'laning",
        'contact-h2': "FORMANI",
        'contact-span': "TO'LDIRING",
        'inp-1' : "ismizni kiriting*",
        'send' : 'YUBORISH',
        'info' : 'Info',
        'all': 'hamma productlar',
        'reviews': 'sharhlar',
        'contact': "biz bilan bog'lanish",
        'network' : 'Ijtimoiy tarmoqlarimiz',
        'rights' : ' Xamma huquqlar himoyalangan © 2022',
        'interesting' : 'Qiziqarli malumotlar',
        'about' : ' HAQIDA',
        'pillow-sp' : "- bu qulay uyqu uchun maxsus ishlab chiqilgan mahsulot. U umurtqa pog'onasi uchun tabiiy holatni kafolatlaydi, bachadon bo'yni va ko'krak bo'limlari to'g'ri chiziq tortadi, intervertebral disklarda ortiqcha yuk bo'lmaydi.To'lqinsimon shakl yotgan holatda bo'yin uchun zarur tayanch hosil qiladi. Yostiqning ortopedik xususiyatlari sog'lom uyqu, to'liq dam olish, tunda tiklanish va ertalab quvnoqlikni ta'minlaydi. Bundan tashqari, u yuqori plastiklikka ega va yukni yostiqning butun yuzasiga teng ravishda taqsimlaydi.",
        'main1' : 'ASOSIY',
        'main2' : 'XUSUSIYATLAR',
        'main-p' : "Sog'ligingiz uchun yuqori sifatli korrektorlarimizni  xarid qiling",
        'material' : "Material",
        'repeir' : "Davolash va oldini olish",
        'ekologiya' : "Ekologiya va ergonomika",
        'use' : 'FOYDALANISH UCHUN',
        'show' : "KO'RSATMALAR",
        'bandaj2' : 'Echib olinadigan tizza bandaji',
        'contact-title' : 'Nima buyurtma',
        'contact-text' : 'bermoqchisiz?',
        'product': 'MAHSULOT',
        'about-korset' : " umurtqa pog'onasi kasalliklari, egriligi va shikastlanishlarida qo'llaniladigan maxsus qattiqlashtiruvchi va tortuvchi tasmalar bilan nafas oladigan, elastik matodan tayyorlangan tibbiy ortopedik kamar. Millionlab odamlar bel og'rig'idan azob chekishadi. Ko'pincha og'riq sindromi pastki orqa qismga davriy noto'g'ri og'irlik o'tkazish natijasida yuzaga keladi. Shunday qilib, orqa tayanch bu yukni engillashtirishga yordam beradi va shu bilan umurtqa pog'onasi, intervertebral disklar va pastki orqa mushaklarning bo'g'imlariga ta'sir qiladigan bosimni kamaytiradi. Yukni tushirish mushaklarning og'riqli kuchlanishini yo'q qiladi va shu bilan umurtqa pog'onasining sog'lom holatini ta'minlaydi. Orqa tirgaklar umurtqa pog'onasining qo'shimcha barqarorligini ta'minlaydi, har qanday faoliyat paytida og'riq va noqulaylikni qoplaydi, shuningdek, turli xil jarohatlar va sharoitlarni davolash va tiklashga yordam beradi.",
        'about-vorotnik' : "- bu bo'yin harakatlarini cheklaydigan yumshoq bo'yinbog'. Yumshoq ko'pikdan yasalgan bo'lib, bo'yniga o'raladi va orqa tomondan mahkamlanadi. Servikal bo'yinbog' bilan fiksatsiya mushaklarning spazmlarini davolash, servikal mintaqadagi harakatlarni barqarorlashtirish va cheklash uchun ishlatiladi.",
        'about-bandaj' : "- bu tizza bo'g'imi hududida kiyiladigan va uni barqarorlashtirish va patellani barqarorlashtirish, meniskus va ligamentlarni qo'llab-quvvatlash uchun ishlatiladigan ortopedik oyoq qavs. Bozorda bir nechta turdagi mahsulotlar mavjud bo'lib, ular birgalikda 'tizzalar' deb ataladi, ammo turli funktsiyalarni bajaradilar va turli tibbiy ko'rsatkichlar uchun buyuriladi. Ba'zi turdagi tizzalar o'z-o'zidan Sotibolish bo'lishi mumkin, boshqalari faqat shifokor, murabbiy yoki fizioterapevt tavsiyasiga binoan tanlanadi. Qanday bo'lmasin, ko'pincha tajribasiz iste'molchi bu nima ekanligini - tizza prokladkalari va qaysi turdagi mahsulot unga mos kelishini to'liq tushunmaydi. Ayniqsa, bunday holatlar uchun biz batafsil maqola tayyorladik, unda biz ortopedik tizzalarning asosiy turlarini, ularning funktsiyasi va qo'llanilishi xususiyatlarini ko'rib chiqamiz.",
        'podushka-p1' : "Osteoxondroz intervertebral disklarning degeneratsiyasidan kelib chiqadi.",
        'podushka-p2' : "Miyaning qon aylanishining buzilishi bilan bog'liq bosh og'rig'i va vertebrobasilar etishmovchiligi.",
        'podushka-p3' : "Bo'yinning mushaklaridagi og'riq va ularning yallig'lanishi, uyqu paytida stressning kuchayishi bilan qo'zg'atiladi.",
        'podushka-p4' : "Vestibulyar apparatlarning buzilishi.",
        'podushka-p5' : "Uzoq muddatli statik tana holati yoki stereotipik ravishda takrorlanadigan harakatlar natijasida kelib chiqqan mushaklar muvozanati.",
        'karset-p1' : "Kuchli egilish, zaiflashgan dorsal mushaklar.",
        'karset-p2' : "Orqa miya mintaqasining o'tkir yoki surunkali kasalliklari.",
        'karset-p3' : "Orqa miyaning konjenital yoki surunkali kasalliklari.",
        'karset-p4' : "Mushak-skelet tizimining lezyonlarini oldini olish.",
        'karset-p5' : "Orqa miyaning turli kasalliklarida normal holatni saqlash.",
        'bandaj-p1': "Tizza bo'g'imlari hududida ko'karishlar.",
        'bandaj-p2': "Harakat paytida va dam olishda tizza bo'g'imidagi og'riq.",
        'bandaj-p3': "Tizza qo'shilishining engil beqarorligi.",
        'bandaj-p4': "Artroz, artrit, sinusit, bursit bilan tizza sohasidagi shish.",
        'bandaj-p5': "Tizza bo'g'imlarida surunkali yallig'lanish kasalliklarining kuchayishining oldini olish (artrit, bursit, sinovit, artroz).",
        'vorotnik-p1' : "Boshqa tabiatning bo'yin va orqa qismida og'riq..",
        'vorotnik-p2' : "Orqa miya degenerativ-distrofik kasalliklari.",
        'vorotnik-p3' : "Jag' sohasidagi yog'ning ortiqcha cho'kishi.",
        'vorotnik-p4' : "Servikal spondiloz, bachadon bo'yni radikulit sindromi.",
        'vorotnik-p5' : "Jarohatlardan keyin reabilitatsiya, servikal umurtqa pog'onasida operatsiyadan keyingi sharoitlar, churrali disklarni jarrohlik davolashdan keyin reabilitatsiya.",
        'privacy-h3': "Qo'llab-quvvatlash",
        'privacy-p1': 'Huquqiy siyosat',
        'privacy-p2': 'Maxfiylik siyosati',
        'privacy-p3': 'Xizmat shartlari',
    },

}